apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - targetPort: db-in
      nodePort: 31433
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres
    ports:
      - name: db-in
        containerPort: 1433
    env:
      - name: POSTGRES_USER
        value: svc-bikerental
      - name: POSTGRES_PASSWORD
        value: bikeadmin123